In [179]:
import numpy as np
%precision 

'%.4f'

In [11]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [12]:
arr = np.arange(10)

In [13]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
arr[5:8] = 64

In [66]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [67]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [69]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [71]:
data = np.random.randn(7, 4)

In [72]:
data

array([[-0.58778061, -0.43471289, -0.25359268,  0.73922024],
       [ 0.65957812,  0.46650723,  0.0144787 , -0.54710054],
       [ 0.09332746, -1.42520451, -0.56994526,  0.09137086],
       [ 0.43030225,  0.80746114, -1.44690617,  0.95339552],
       [-1.01232008, -0.67932509,  0.06818438, -0.39819616],
       [-1.30150494,  0.08724193,  0.89558908,  0.58188525],
       [ 1.12747525,  1.5050779 ,  0.09708568,  0.85991478]])

In [73]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [74]:
data[names=='Bob']

array([[-0.58778061, -0.43471289, -0.25359268,  0.73922024],
       [ 0.43030225,  0.80746114, -1.44690617,  0.95339552]])

In [75]:
data[names=='Bob', 2:]

array([[-0.25359268,  0.73922024],
       [-1.44690617,  0.95339552]])

In [76]:
-True==False

False

In [78]:
mask = (names == 'Bob') | (names == 'Will')

In [79]:
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [80]:
data[mask]

array([[-0.58778061, -0.43471289, -0.25359268,  0.73922024],
       [ 0.09332746, -1.42520451, -0.56994526,  0.09137086],
       [ 0.43030225,  0.80746114, -1.44690617,  0.95339552],
       [-1.01232008, -0.67932509,  0.06818438, -0.39819616]])

In [96]:
alpha_data = np.array(['a', 'b', 'c', 'd', 'e'])
nums = np.random.randint(10, size=5)

In [97]:
alpha_data[(nums%2==0)]

array(['a', 'b'], 
      dtype='<U1')

In [98]:
nums

array([4, 4, 3, 1, 1])

In [102]:
data

array([[-0.58778061, -0.43471289, -0.25359268,  0.73922024],
       [ 0.65957812,  0.46650723,  0.0144787 , -0.54710054],
       [ 0.09332746, -1.42520451, -0.56994526,  0.09137086],
       [ 0.43030225,  0.80746114, -1.44690617,  0.95339552],
       [-1.01232008, -0.67932509,  0.06818438, -0.39819616],
       [-1.30150494,  0.08724193,  0.89558908,  0.58188525],
       [ 1.12747525,  1.5050779 ,  0.09708568,  0.85991478]])

In [105]:
data[data < 0] = 0

In [106]:
data

array([[ 0.        ,  0.        ,  0.        ,  0.73922024],
       [ 0.65957812,  0.46650723,  0.0144787 ,  0.        ],
       [ 0.09332746,  0.        ,  0.        ,  0.09137086],
       [ 0.43030225,  0.80746114,  0.        ,  0.95339552],
       [ 0.        ,  0.        ,  0.06818438,  0.        ],
       [ 0.        ,  0.08724193,  0.89558908,  0.58188525],
       [ 1.12747525,  1.5050779 ,  0.09708568,  0.85991478]])

In [107]:
data[names != 'Joe'] = 7

In [133]:
arr = np.arange(15).reshape((3, 5))

In [134]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [135]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [141]:
arr = np.random.randn(6, 3)

In [143]:
np.dot(arr.T, arr)

array([[  6.67834317,   0.793761  ,  -1.47613215],
       [  0.793761  ,  11.55268289,  -1.45706568],
       [ -1.47613215,  -1.45706568,   5.44409949]])

In [171]:
from numpy.random import randn
x = randn(8)
y = randn(8)

In [172]:
x

array([-0.6251611 , -0.19544859,  0.80011981, -0.2480834 , -0.90476916,
        0.90335737, -0.85497378, -1.68744349])

In [173]:
print (x)
print (y)

[-0.6251611  -0.19544859  0.80011981 -0.2480834  -0.90476916  0.90335737
 -0.85497378 -1.68744349]
[-0.55208499  0.21117613  0.15475129 -0.9378524   0.66542684  0.78842345
 -1.19672749  0.13318034]


In [177]:
np.maximum(x, y)

array([-0.5521,  0.2112,  0.8001, -0.2481,  0.6654,  0.9034, -0.855 ,
        0.1332])

In [180]:
x

array([-0.6252, -0.1954,  0.8001, -0.2481, -0.9048,  0.9034, -0.855 ,
       -1.6874])

In [181]:
arr = randn(7) * 5

In [182]:
arr

array([ 0.1764, -5.6437,  4.6794, -9.7533,  0.4542, -6.5135, -5.3587])

In [186]:
np.modf(arr)

(array([ 0.1764, -0.6437,  0.6794, -0.7533,  0.4542, -0.5135, -0.3587]),
 array([ 0., -5.,  4., -9.,  0., -6., -5.]))

In [202]:
a = np.random.randint(25, size=4)
b = np.random.randint(25, size=4)
np.greater(a, b)

array([False, False, False, False], dtype=bool)

In [203]:
a, b

(array([11, 20,  1,  3]), array([19, 23, 22, 22]))

In [213]:
points = np.arange(-5, 5, 0.01)
xs, ys = np.meshgrid(points, points)

In [214]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ..., 
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [220]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ..., 
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [221]:
z = np.sqrt(xs ** 2 + ys ** 2)

In [222]:
z

array([[ 7.0711,  7.064 ,  7.0569, ...,  7.0499,  7.0569,  7.064 ],
       [ 7.064 ,  7.0569,  7.0499, ...,  7.0428,  7.0499,  7.0569],
       [ 7.0569,  7.0499,  7.0428, ...,  7.0357,  7.0428,  7.0499],
       ..., 
       [ 7.0499,  7.0428,  7.0357, ...,  7.0286,  7.0357,  7.0428],
       [ 7.0569,  7.0499,  7.0428, ...,  7.0357,  7.0428,  7.0499],
       [ 7.064 ,  7.0569,  7.0499, ...,  7.0428,  7.0499,  7.0569]])

In [224]:
z.shape

(1000, 1000)

In [225]:
import matplotlib.pyplot as plt

In [228]:
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()

In [229]:
plt.title("Image plot of §\sqrt{x^2 + y^2}§ for a grid of values")

In [231]:
plt.show()

In [285]:
xarr = np.linspace(1, 1.5, 6, endpoint=True)
xarr

array([ 1. ,  1.1,  1.2,  1.3,  1.4,  1.5])

In [286]:
yarr = np.arange(2.0, 2.51, 0.1)
yarr

array([ 2. ,  2.1,  2.2,  2.3,  2.4,  2.5])

In [287]:
cond = np.array([True, False, True, True, False])